In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
df = pd.read_csv(url)
df.isna().sum()

row_n           0
id              1
name            0
gender          0
species         0
birthday        0
personality     0
song           11
phrase          0
full_id         0
url             0
dtype: int64

In [2]:
# General definitions of "observations" and "variables"
# In the context of my dataset observations refer to the individual rows where each row in this case refers to a unique character in from animal crossing 
# In the context of this dataset variables refer the columns in the dataset. This pretty much means the specific attributes/ properties of each character (e.g. name or species..)

In [3]:
# Question #4
# this is the example chatgpt provided on how to i can provide summaries of columns using the code hinted


# import pandas as pd

# Load the dataset
#url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
#villagers = pd.read_csv(url)

# Provide summary statistics for numeric columns
#print("Summary statistics for numeric columns:")
#print(villagers.describe())

# Provide value counts for a categorical column (replace 'species' with any relevant column from your data)
#print("\nValue counts for 'species' column:")
#print(villagers['species'].value_counts())

# Provide value counts for another categorical column (replace 'personality' with any relevant column from your data)
#print("\nValue counts for 'personality' column:")
#print(villagers['personality'].value_counts())

In [4]:
df

,row_n,id,name,gender,species,birthday,personality,song,phrase,full_id,url
0,2,admiral,Admiral,male,bird,1-27,cranky,Steep Hill,aye aye,villager-admiral,https://villagerdb.com/images/villagers/thumb/...
1,3,agent-s,Agent S,female,squirrel,7-2,peppy,DJ K.K.,sidekick,villager-agent-s,https://villagerdb.com/images/villagers/thumb/...
2,4,agnes,Agnes,female,pig,4-21,uchi,K.K. House,snuffle,villager-agnes,https://villagerdb.com/images/villagers/thumb/...
3,6,al,Al,male,gorilla,10-18,lazy,Steep Hill,Ayyeeee,villager-al,https://villagerdb.com/images/villagers/thumb/...
4,7,alfonso,Alfonso,male,alligator,6-9,lazy,Forest Life,it'sa me,villager-alfonso,https://villagerdb.com/images/villagers/thumb/...
...,...,...,...,...,...,...,...,...,...,...,...
386,475,winnie,Winnie,female,horse,1-31,peppy,My Place,hay-OK,villager-winnie,https://villagerdb.com/images/villagers/thumb/...
387,477,wolfgang,Wolfgang,male,wolf,11-25,cranky,K.K. Song,snarrrl,villager-wolfgang,https://villagerdb.com/images/villagers/thumb/...
388,480,yuka,Yuka,female,koala,7-20,snooty,Soulful K.K.,tsk tsk,villager-yuka,https://villagerdb.com/images/villagers/thumb/...
389,481,zell,Zell,male,deer,6-7,smug,K.K. D&B,pronk,villager-zell,https://villagerdb.com/images/villagers/thumb/...
390,483,zucker,Zucker,male,octopus,3-8,lazy,Spring Blossoms,bloop,villager-zucker,https://villagerdb.com/images/villagers/thumb/...

In [5]:
#Question #5
#A method is something that belongs to an object and performs a specific task when called upon. An attribute is a chracteristic of an object
#In this case with df.shape and df.describe(), df.shape can be accessed directly giving information whereas on the otherhand df.describe() is function that performs operations such as calculations. 
#Also df.describe() is used with parenthesis and df.shape does not require them and can be called directly
#Chat session link: https://chatgpt.com/share/ba214a25-f091-46c6-8c77-122595935ddc

In [6]:
#Question 6 
#Count: It counts the total number of non-null observations for each variable provided
#Mean: Finds the average value of the variable provided
#Standard Deviation: This is the measure of the amount of dispersion of the values from the mean 
#Min: finds the minimum value of a dataset 
#25th percentile: This is the area to which 25% of the data falls under (a.k.a the first quartile Q1)
#50th percentile: This is generally refered to as the median/ the middle of the dataset 
#75th percentile: This is known as the third quartile and this is where 75 percent of the data falls under
#Maximum: This is the largest value within a set of data 
#chatbot session link: https://chatgpt.com/share/5183e830-b3a8-41e8-a2fd-61d20c51be9a

In [7]:
#Question 7
#df.dropna(): This is useful for dropping row with missing values.  If you wanted to analyze your data with full information(nothing missing) this will drop the missing data points. This is preffered over del df['col'] if deleting information isnt important 
#del df['col']: Preferred when a column has many missing values but the remaining columns are complete and valuable such as when removing an unimportant column with lots of missing data to save the rest of the dataset
#One before the other: Removing unnecessary columns first avoids losing rows that could be valuable if missing data is only in specific columns, ensuring a cleaner and more relevant dataset
#chatbot session Link: https://chatgpt.com/share/982f5d5e-708e-4fde-9dd5-f36ace6c30bd

In [10]:
import pandas as pd


url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
df = pd.read_csv(url)


print("Before manipulation:")
missing_values_before = df.isna().sum()
print(missing_values_before)

columns_to_remove = ['color', 'birthday']
for col in columns_to_remove:
    if col in df.columns:
        del df[col]


df_cleaned = df.dropna()


print("\nAfter manipulation:")
missing_values_after = df_cleaned.isna().sum()
print(missing_values_after)


print("\nFirst few rows of the cleaned dataset:")
print(df_cleaned.head())

Before manipulation:
row_n           0
id              1
name            0
gender          0
species         0
birthday        0
personality     0
song           11
phrase          0
full_id         0
url             0
dtype: int64

After manipulation:
row_n          0
id             0
name           0
gender         0
species        0
personality    0
song           0
phrase         0
full_id        0
url            0
dtype: int64

First few rows of the cleaned dataset:
   row_n       id     name  gender    species personality         song  \
0      2  admiral  Admiral    male       bird      cranky   Steep Hill
1      3  agent-s  Agent S  female   squirrel       peppy      DJ K.K.
2      4    agnes    Agnes  female        pig        uchi   K.K. House
3      6       al       Al    male    gorilla        lazy   Steep Hill
4      7  alfonso  Alfonso    male  alligator        lazy  Forest Life

     phrase           full_id  \
0   aye aye  villager-admiral
1  sidekick  villager-agent-s
2   snuffle    villager-agnes
3   Ayyeeee       villager-al
4  it'sa me  villager-alfonso

                                                 url
0  https://villagerdb.com/images/villagers/thumb/...
1  https://villagerdb.com/images/villagers/thumb/...
2  https://villagerdb.com/images/villagers/thumb/...
3  https://villagerdb.com/images/villagers/thumb/...
4  https://villagerdb.com/images/villagers/thumb/...

In [11]:
#JUSTIFICATIONL
#Removing columns with alot of missing data help you focus on the more important parts of the dataset. Applying df.dropna() afterward ensures that the remaining data is complete and not missing.

In [6]:
#Question #8 __________________________________________________________________________________________________

In [4]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

In [5]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [7]:
#df.groupby("col1")["col2"].describe() is used to isolate information in a way. the ("col1") will select a specific column within your dataset and then ["col2"] will group it further using it to describe a specific set of data

In [10]:
#Example 1
age_class_summury = df.groupby("age")["class"].describe()
age_class_summury
#this will take the ages of all the passengers from youngest to oldest and will show what class they were in on the titanic

      count unique     top freq
age
0.42      1      1   Third    1
0.67      1      1  Second    1
0.75      2      1   Third    2
0.83      2      1  Second    2
0.92      1      1   First    1
...     ...    ...     ...  ...
70.00     2      2  Second    1
70.50     1      1   Third    1
71.00     2      1   First    2
74.00     1      1   Third    1
80.00     1      1   First    1

[88 rows x 4 columns]

In [11]:
#8 - 2
#The reason why it comes up with something different is due to how each command handles missing (NaN) values 
#df.describe() does the statistics only for non NaN values in each column independently. Therefore the count for each column is the number of non NaN values 
#---> also for df.describe() the are only evaluated on a column by column basis and not how the columns interact
#df.groupby("col1")["col2"].describe() This command. evaluates missing data a little bit differently. For example if i were to group for col1 it will ignore all missing values entirely and in a way remove them from the new dataset being made.
#--->Same thing goes for the ["col2"] section, if there are missing values it will reduce the count for that group

In [1]:
#errorA
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df

NameError: name 'pd' is not defined

In [2]:
#I found that using ChatBot was alot quicker. When googling it I had to go into stack overflow and then check for the solution whereas ChatBot showed me the code directly and quickly with a brief explanation 
#LINK TO CHATGPT SESSION: https://chatgpt.com/share/30517bc5-e3dc-4c8b-a9fa-fd103faaf89a

In [7]:
#errorB
import pandas as pd
url = "titanics.csv"
df = pd.read_csv(url)
#GPT session link: https://chatgpt.com/share/a2fb94d7-42a7-41d1-b133-82b92d9ff5ea
#I found that ChatBot was alot more useful in this case as it could pick out what was specifically wrong with the code
# --> the google search was also helpul as it knew what to check for but once again I found chatBot more useful as it did the searching for me/ troubleshooting

FileNotFoundError: [Errno 2] No such file or directory: 'titanic.csv'

In [8]:
import pandas as pd
url = "https://raw.githubusercontent.comseaborn-data/master/titanic.csv"
df = pd.read_csv(url)

URLError: <urlopen error [Errno -2] Name or service not known>

In [1]:
#errorC
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
age_class_summury = df.groupby("age")["class"].describe()
age_class_summury

df = pd.read_csv(url)

#Once again I found the chatbot alot easier. Its similair to the last question as it picked out the specific error within the code and told me what possibly was wrong. 
#The google search also gave me a general reasoning like the last error but chatBot gave me the same answer and helped search for what was wrong within the code.
#ChatBot Session Link: https://chatgpt.com/share/59699a18-3bbd-40ff-9028-41d46e0900db

NameError: name 'df' is not defined

In [14]:
#errorD
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url

SyntaxError: incomplete input (527436294.py, line 4)

In [15]:
#I found that between the google search and chatBot the chatBot was defininelty more helpful since it picked out what was wrong right away
#The google search on the other hand didn't really know my specific problem and actually showed me different material for a different error unrelated
#In general thoguh I found the error given by Jupyter to be the most useful since this is only a small error.
#Chatbot Session Link: https://chatgpt.com/share/6c8b6f23-eac2-4d38-9748-d4f42db03445

In [2]:
#errorE
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
age_class_summury = df.groupby("age")["class"].describle()
age_class_summury

AttributeError: 'SeriesGroupBy' object has no attribute 'describle'

In [3]:
#I found chatbot here to be easier since it pointed out the exact problem.
#The google search also gave me a general reasoning like the last error but chatBot gave me the same answer and helped search for what was wrong within the code.
#ChatBot Session Link: https://chatgpt.com/share/c63ce5ee-2b0a-4be9-9d2c-b8956ad626e8

In [4]:
#errorF
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
age_class_summury = df.groupby("SEX")["class"].describe()
age_class_summury

KeyError: 'SEX'

In [5]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
age_class_summury = df.groupby("age")["CLASS"].describle()
age_class_summury

KeyError: 'Column not found: CLASS'

In [6]:
#Like the past examples I found that chatBot was once again more useful than a google search. This is because when I searched it up on google it gave me a general answer but I'd still have to keep looking through my code whereas chatbot identtified the problem directly
#Chatbot Session Link: https://chatgpt.com/share/bf2a3667-9801-42b9-8ca8-242f878c1be

In [10]:
#errorG
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
age_class_summury = df.groupby(age)["class"].describe()
age_class_summury

NameError: name 'age' is not defined

In [9]:
#errorG
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
age_class_summury = df.groupby("age")[class].describe()
age_class_summury

SyntaxError: invalid syntax (4039754414.py, line 5)

In [11]:
#I found google and chatgpt to be very similair for this error although like the other responses chatgpt was definitely more useful as it showed a physical picture and example fo what happened.
#In general though I found the built in error system in jupyter to be the most useful 
#Chatbot session Link: https://chatgpt.com/share/00eec9be-0289-4f8b-89d9-67701b618b85

In [ ]:
#question9
#Answer: Somewhat